### ISSUE TITLE
Please tell me the license

### ISSUE THREAD

**Issue by ES0729dhun** [zh/redmine_importer#37]
Please tell me the license of this plug-in.

If there is no license, please tell me the following information：
1. Is this plug-in free?
2. Can I use this plug-in for commercial?

**Comment by zh** [comment]
Hm, according to [this discussion](http://www.redmine.org/boards/4/topics/27405?r=37731) seems all Redmine plugins should be under GPL licence. As for me, I don't care how you'll use the plugin, it is open sourced. It is even not mine, but a fork of the leovitch/redmine_importer repository.

**Comment by ES0729dhun** [comment]
One more question, please tell me the GPL version(GPL v2 or GPL v3).

**Comment by ES0729dhun** [comment]
> As for me, I don't care how you'll use the plugin, it is open sourced. 

I want to extend the Redmine of function(will not customize the source cord).
I will only use the CSV import in Redmine.

**Comment by zh** [comment]
I also think it is GPL v2

**Comment by ES0729dhun** [comment]
Thank you very much.
